FROM ubuntu
RUN apt -y update
RUN apt -y install build-essential
RUN apt -y install cmake
RUN apt -y install python
RUN apt -y install git
RUN git clone https://github.com/emscripten-core/emsdk.git /home/webassembly/emsdk
