FROM ubuntu
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python \
    openjdk-8-jdk-headless \
    git
RUN git clone https://github.com/emscripten-core/emsdk.git /home/webassembly/emsdk